name: Check Code Style

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "ESLint"

    runs-on: self-hosted

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
